<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 4,
                'sl' => 1,
                'menu_section_id' => 2,
                'parent_id' => NULL,
                'name' => 'Dashboard',
                'system_name' => 'Dashboard',
                'route' => 'dashboard',
                'slug' => 'index',
                'icon' => 'fa fa-home',
                'type' => 3,
                'status' => 1,
                'created_at' => '2025-12-08 16:45:13',
                'updated_at' => '2025-12-08 16:45:13',
            ),
            1 => 
            array (
                'id' => 5,
                'sl' => 2,
                'menu_section_id' => 3,
                'parent_id' => NULL,
                'name' => 'Developer Menu',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-bars',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-08 16:45:33',
                'updated_at' => '2025-12-08 16:45:33',
            ),
            2 => 
            array (
                'id' => 6,
                'sl' => 3,
                'menu_section_id' => 3,
                'parent_id' => 5,
                'name' => 'Menu Section',
                'system_name' => 'Menu Section',
                'route' => 'menu_section',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-08 16:46:52',
                'updated_at' => '2025-12-08 16:46:52',
            ),
            3 => 
            array (
                'id' => 7,
                'sl' => 4,
                'menu_section_id' => 3,
                'parent_id' => 5,
                'name' => 'Menu',
                'system_name' => 'Menu',
                'route' => 'menu',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-08 16:47:12',
                'updated_at' => '2025-12-08 16:47:12',
            ),
            4 => 
            array (
                'id' => 8,
                'sl' => 5,
                'menu_section_id' => 4,
                'parent_id' => NULL,
                'name' => 'User Management',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-users',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-08 17:10:36',
                'updated_at' => '2025-12-08 17:10:36',
            ),
            5 => 
            array (
                'id' => 9,
                'sl' => 6,
                'menu_section_id' => 4,
                'parent_id' => 8,
                'name' => 'Role',
                'system_name' => 'Role',
                'route' => 'role',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-08 17:11:03',
                'updated_at' => '2025-12-08 17:11:03',
            ),
            6 => 
            array (
                'id' => 10,
                'sl' => 7,
                'menu_section_id' => 4,
                'parent_id' => 8,
                'name' => 'User',
                'system_name' => 'User',
                'route' => 'user',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-08 17:11:29',
                'updated_at' => '2025-12-08 17:11:29',
            ),
            7 => 
            array (
                'id' => 11,
                'sl' => 8,
                'menu_section_id' => 5,
                'parent_id' => NULL,
                'name' => 'Website Content',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-gear',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-08 18:14:59',
                'updated_at' => '2025-12-08 18:14:59',
            ),
            8 => 
            array (
                'id' => 12,
                'sl' => 9,
                'menu_section_id' => 5,
                'parent_id' => 11,
                'name' => 'Website Settings',
                'system_name' => 'Website Settings',
                'route' => 'website_settings',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-08 18:16:06',
                'updated_at' => '2025-12-08 18:16:06',
            ),
            9 => 
            array (
                'id' => 13,
                'sl' => 10,
                'menu_section_id' => 6,
                'parent_id' => NULL,
                'name' => 'Product Components',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-14 18:12:24',
                'updated_at' => '2025-12-14 18:12:24',
            ),
            10 => 
            array (
                'id' => 15,
                'sl' => 12,
                'menu_section_id' => 6,
                'parent_id' => 13,
                'name' => 'Item',
                'system_name' => 'Item',
                'route' => 'item',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-14 18:17:58',
                'updated_at' => '2025-12-14 18:25:51',
            ),
            11 => 
            array (
                'id' => 16,
                'sl' => 13,
                'menu_section_id' => 6,
                'parent_id' => 13,
                'name' => 'Category',
                'system_name' => 'Category',
                'route' => 'category',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-14 18:27:51',
                'updated_at' => '2025-12-14 18:27:51',
            ),
            12 => 
            array (
                'id' => 17,
                'sl' => 14,
                'menu_section_id' => 6,
                'parent_id' => 13,
                'name' => 'Brand',
                'system_name' => 'Brand',
                'route' => 'brand',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-14 18:29:13',
                'updated_at' => '2025-12-14 18:29:13',
            ),
            13 => 
            array (
                'id' => 18,
                'sl' => 15,
                'menu_section_id' => 6,
                'parent_id' => 13,
                'name' => 'Unit',
                'system_name' => 'Unit',
                'route' => 'unit',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-16 06:26:02',
                'updated_at' => '2025-12-16 06:26:02',
            ),
            14 => 
            array (
                'id' => 19,
                'sl' => 16,
                'menu_section_id' => 6,
                'parent_id' => 13,
                'name' => 'Sub Unit',
                'system_name' => 'Sub Unit',
                'route' => 'sub_unit',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-16 06:26:37',
                'updated_at' => '2025-12-16 06:26:37',
            ),
            15 => 
            array (
                'id' => 20,
                'sl' => 17,
                'menu_section_id' => 6,
                'parent_id' => NULL,
                'name' => 'Product Information',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-bars',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-16 15:59:13',
                'updated_at' => '2025-12-16 15:59:13',
            ),
            16 => 
            array (
                'id' => 21,
                'sl' => 18,
                'menu_section_id' => 6,
                'parent_id' => 20,
                'name' => 'Product',
                'system_name' => 'Product',
                'route' => 'product',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-16 15:59:44',
                'updated_at' => '2025-12-16 15:59:44',
            ),
            17 => 
            array (
                'id' => 22,
                'sl' => 19,
                'menu_section_id' => 7,
                'parent_id' => NULL,
                'name' => 'Supplier Information',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-user',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-17 16:57:18',
                'updated_at' => '2025-12-17 16:57:18',
            ),
            18 => 
            array (
                'id' => 23,
                'sl' => 20,
                'menu_section_id' => 7,
                'parent_id' => 22,
                'name' => 'Supplier Info',
                'system_name' => 'Supplier',
                'route' => 'supplier',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-17 16:57:43',
                'updated_at' => '2025-12-17 16:57:43',
            ),
            19 => 
            array (
                'id' => 24,
                'sl' => 21,
                'menu_section_id' => 8,
                'parent_id' => NULL,
                'name' => 'Purchase Info',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-cash',
                'type' => 1,
                'status' => 1,
                'created_at' => '2025-12-19 14:22:56',
                'updated_at' => '2025-12-19 14:22:56',
            ),
            20 => 
            array (
                'id' => 25,
                'sl' => 22,
                'menu_section_id' => 8,
                'parent_id' => 24,
                'name' => 'Purchase',
                'system_name' => 'Purchase',
                'route' => 'purchase',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2025-12-19 14:23:18',
                'updated_at' => '2025-12-19 14:23:18',
            ),
            21 => 
            array (
                'id' => 26,
                'sl' => 23,
                'menu_section_id' => 9,
                'parent_id' => NULL,
                'name' => 'Stock',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-layer',
                'type' => 1,
                'status' => 1,
                'created_at' => '2026-01-11 17:27:54',
                'updated_at' => '2026-01-11 17:27:54',
            ),
            22 => 
            array (
                'id' => 27,
                'sl' => 24,
                'menu_section_id' => 9,
                'parent_id' => 26,
                'name' => 'Warehouse Stock',
                'system_name' => 'Warehouse Stock',
                'route' => 'warehouse_stock',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-01-11 17:28:53',
                'updated_at' => '2026-01-11 17:28:53',
            ),
            23 => 
            array (
                'id' => 28,
                'sl' => 25,
                'menu_section_id' => 10,
                'parent_id' => NULL,
                'name' => 'Driver Info',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'type' => 1,
                'status' => 1,
                'created_at' => '2026-01-25 16:52:06',
                'updated_at' => '2026-01-25 16:52:06',
            ),
            24 => 
            array (
                'id' => 29,
                'sl' => 26,
                'menu_section_id' => 10,
                'parent_id' => 28,
                'name' => 'Create Driver',
                'system_name' => 'Driver',
                'route' => 'driver',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-01-25 16:52:52',
                'updated_at' => '2026-01-25 16:52:52',
            ),
            25 => 
            array (
                'id' => 30,
                'sl' => 27,
                'menu_section_id' => 10,
                'parent_id' => 28,
                'name' => 'Driver Issue',
                'system_name' => 'Driver Issue',
                'route' => 'driver-issues',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-01-27 17:57:34',
                'updated_at' => '2026-01-27 17:57:34',
            ),
            26 => 
            array (
                'id' => 31,
                'sl' => 28,
                'menu_section_id' => 11,
                'parent_id' => NULL,
                'name' => 'Customer',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-users',
                'type' => 1,
                'status' => 1,
                'created_at' => '2026-02-04 18:47:54',
                'updated_at' => '2026-02-04 18:47:54',
            ),
            27 => 
            array (
                'id' => 32,
                'sl' => 29,
                'menu_section_id' => 11,
                'parent_id' => 31,
                'name' => 'Customer Area',
                'system_name' => 'Customer Area',
                'route' => 'customer_area',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-02-04 18:48:19',
                'updated_at' => '2026-02-04 18:48:19',
            ),
            28 => 
            array (
                'id' => 33,
                'sl' => 30,
                'menu_section_id' => 11,
                'parent_id' => 31,
                'name' => 'Customer',
                'system_name' => 'Customer',
                'route' => 'customer',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-02-04 18:48:46',
                'updated_at' => '2026-02-04 18:48:46',
            ),
            29 => 
            array (
                'id' => 34,
                'sl' => 31,
                'menu_section_id' => 12,
                'parent_id' => NULL,
                'name' => 'Website Settings',
                'system_name' => 'Website Settings',
                'route' => 'website_settings',
                'slug' => 'index',
                'icon' => 'fa fa-gears',
                'type' => 3,
                'status' => 1,
                'created_at' => '2026-02-16 18:05:29',
                'updated_at' => '2026-02-16 18:05:29',
            ),
            30 => 
            array (
                'id' => 35,
                'sl' => 32,
                'menu_section_id' => 13,
                'parent_id' => NULL,
                'name' => 'Sales Information',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-layer',
                'type' => 1,
                'status' => 1,
                'created_at' => '2026-02-16 18:10:26',
                'updated_at' => '2026-02-16 18:10:26',
            ),
            31 => 
            array (
                'id' => 36,
                'sl' => 33,
                'menu_section_id' => 13,
                'parent_id' => 35,
                'name' => 'Sales Ledger',
                'system_name' => 'Sales Ledger',
                'route' => 'sales',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-02-16 18:11:04',
                'updated_at' => '2026-02-16 18:11:04',
            ),
            32 => 
            array (
                'id' => 37,
                'sl' => 34,
                'menu_section_id' => 14,
                'parent_id' => NULL,
                'name' => 'Income Expense',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-layer',
                'type' => 1,
                'status' => 1,
                'created_at' => '2026-02-16 18:14:29',
                'updated_at' => '2026-02-16 18:14:29',
            ),
            33 => 
            array (
                'id' => 38,
                'sl' => 35,
                'menu_section_id' => 14,
                'parent_id' => 37,
                'name' => 'Income Expense Title',
                'system_name' => 'Income Expense Title',
                'route' => 'income_expense_title',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-02-16 18:15:15',
                'updated_at' => '2026-02-16 18:15:15',
            ),
            34 => 
            array (
                'id' => 39,
                'sl' => 36,
                'menu_section_id' => 14,
                'parent_id' => 37,
                'name' => 'Expense Entry',
                'system_name' => 'Expense Entry',
                'route' => 'expense_entry',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-02-16 18:15:57',
                'updated_at' => '2026-02-16 18:15:57',
            ),
            35 => 
            array (
                'id' => 40,
                'sl' => 37,
                'menu_section_id' => 14,
                'parent_id' => 37,
                'name' => 'Income Entry',
                'system_name' => 'Income Entry',
                'route' => 'income_entry',
                'slug' => 'index',
                'icon' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => '2026-02-16 18:16:25',
                'updated_at' => '2026-02-16 18:16:25',
            ),
        ));
        
        
    }
}